### PR TITLE
Update to embedded-hal 1.0

### PR DESCRIPTION
**Pull request by t-moe**

### CODE REVIEW

**Comment by t-moe** [comment]
This was merged, but it doesnt appear on main?
Where did we loose this commit?

**Comment by ost-ing** [comment]
@t-moe Strange, not entirely sure what happened, I suspect there was an issue when I rewrote some git history recently to update my git author/email

**Comment by ost-ing** [comment]
@t-moe should be restored now, and its up on crates.io https://crates.io/crates/lp50xx

**Comment by t-moe** [comment]
seems to work. thank you

**Pull request merged**
